#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "esp_err.h"
#include "bsp/esp-bsp.h"
#include "driver/usb_serial_jtag.h"
#include "driver/usb_serial_jtag_vfs.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "aura_services.h"
#include "aura_wifi.h"
#include "aura_ui.h"
#include "aura_motion.h"
static void command(char *line) {
    long long epoch; int value;
    if (sscanf(line, "TIME %lld %d", &epoch, &value)==2) {
        printf("AURA_TIME %s\n", esp_err_to_name(aura_clock_set((time_t)epoch,value)));
    } else if (!strcmp(line,"STATUS")) {
        aura_wifi_status_t wifi; aura_wifi_get_status(&wifi);
        aura_motion_status_t motion; aura_motion_get_status(&motion);
        printf("AURA_STATUS epoch=%lld valid=%d rtc=%d offset=%d brightness=%d theme=%d clock=%s wifi=%d configured=%d ssid=%s reason=%u last_sync=%lld imu=%d xyz=%.2f,%.2f,%.2f movement=%.2f rotation=%.1f shakes=%u\n",(long long)time(NULL),aura_clock_valid(),aura_rtc_available(),aura_clock_offset(),aura_brightness(),aura_theme(),aura_clock_24h()?"24h":"12h",wifi.state,wifi.configured,wifi.configured?wifi.ssid:"-",wifi.disconnect_reason,(long long)wifi.last_sync,motion.available,motion.x,motion.y,motion.z,motion.movement,motion.rotation,motion.shake_count);
    } else if (!strcmp(line,"WIFI_SETUP")) {
        aura_wifi_start_setup(); printf("AURA_WIFI setup\n");
    } else if (!strcmp(line,"WIFI_SYNC")) {
        aura_wifi_request_sync(); printf("AURA_WIFI sync\n");
    } else if (!strcmp(line,"WIFI_FORGET")) {
        aura_wifi_forget(); printf("AURA_WIFI forgotten\n");
    } else {
        bsp_display_lock(0);
        if (!strcmp(line,"SCREEN")) aura_ui_dump_screen();
        else if (sscanf(line,"PAGE %d",&value)==1 && value>=0 && value<5) aura_ui_page(value);
        else if (sscanf(line,"TIMER %d",&value)==1 && value>0 && value<=86400) aura_ui_timer_start(value);
        else if (!strcmp(line,"SLEEP")) aura_ui_sleep(1);
        else if (!strcmp(line,"WAKE")) aura_ui_sleep(0);
        else if (!strcmp(line,"PWR_SHORT")) aura_ui_power_short();
        else if (!strcmp(line,"PWR_LONG")) aura_ui_power_long();
        else if (!strcmp(line,"PWR_RELEASE")) aura_ui_power_release();
        else if (!strcmp(line,"DIZZY")) aura_ui_dizzy();
        else printf("AURA_ERROR unknown command\n");
        bsp_display_unlock();
    }
    fflush(stdout);
}
static void serial_task(void *unused) {
    char line[128]; size_t length=0; bool overflow=false;
    for (;;) {
        char c;
        if(usb_serial_jtag_read_bytes(&c,1,pdMS_TO_TICKS(100))!=1) continue;
        if(c=='\n') {
            if(!overflow) { line[length]=0; command(line); }
            else printf("AURA_ERROR line too long\n");
            length=0; overflow=false;
        } else if(c!='\r') {
            if(length<sizeof(line)-1) line[length++]=c; else overflow=true;
        }
    }
}
static void power_button_task(void *unused) {
    (void)unused;
    bool long_active=false;
    // Ignore the release event generated by the same PWR hold that started the watch.
    vTaskDelay(pdMS_TO_TICKS(2000));
    aura_power_button_events();
    for (;;) {
        uint8_t events=aura_power_button_events();
        if(events) {
            bool held=long_active || (events & (1<<2));
            bsp_display_lock(0);
            if(events & (1<<2)) { long_active=true; aura_ui_power_long(); }
            if((events & (1<<0)) && long_active) { long_active=false; aura_ui_power_release(); }
            if((events & (1<<3)) && !held) aura_ui_power_short();
            bsp_display_unlock();
        }
        vTaskDelay(pdMS_TO_TICKS(80));
    }
}
void app_main(void) {
    if(!bsp_display_start()) return;
    aura_services_init();
    aura_wifi_init();
    bsp_display_lock(0); aura_ui_init(); bsp_display_unlock();
    aura_motion_init();
    usb_serial_jtag_driver_config_t config={.tx_buffer_size=4096,.rx_buffer_size=256};
    ESP_ERROR_CHECK(usb_serial_jtag_driver_install(&config));
    usb_serial_jtag_vfs_use_driver();
    xTaskCreate(serial_task,"aura_serial",8192,NULL,3,NULL);
    xTaskCreate(power_button_task,"aura_pwr",4096,NULL,4,NULL);
    printf("AURA_READY Basic 1.2 dev.3\n");
}
